### ISSUE TITLE
secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by EngineMaster** [nestjs/jwt#1063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

"@nestjs/core": "^9.0.0",
 "@nestjs/jwt": "^9.0.0",

registering module this way: 
JwtModule.registerAsync({
      useFactory: () => ({
        secret: 'some_random_secret',
        signOptions: {
          expiresIn: '30m'
        },
        

But when trying to sign with JwtService I am recieving error: "message": "secretOrPrivateKey must have a value",

What can cause this problem?

### Minimum reproduction code

{     "message": "secretOrPrivateKey must have a value",     "success": false }

### Expected behavior

Expected behavior is not to ask about secretOrPrivateKey that is a deprecated option  

### Package version

9.0.0

### NestJS version

9.0.0

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please use our [Discord](https://discord.gg/nestjs)

btw there are several questions on this subject on StackOverflow as well

---

If you believe that this is a bug, provide a minimum reproduction repository.

# [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by RUPAAK** [comment]
@EngineMaster  have you solved this issue ?

**Comment by newTap** [comment]
> 

It's true that you can't introduce JwtService into Module, otherwise options will be overwritten, not sure why

**Comment by beerbear-man** [comment]
Thanks for @RUPAAK and @newTap . Your advice is also valid for 2024.
I was struggling with the same problem, but I found the answer.
First of all, I think [this](https://github.com/nestjs/jwt/blob/7e0fdf6a2ad87399924e0d9d171d58daf6398bd3/lib/jwt.service.ts#L18) is the reason why JwtService option is overwritten when it is introduced in Module.

If you want to use JwtModule on the other Module like this
```
@Module({
  imports: [JwtModule.regster(...)]
})
export class JwtProviderModule {}

@Module({
  imports: [JwtProviderModule],
  controllers: [],
  providers: [/* do not introduce JwtService */],
})
export class AppModule {
}

```

you can use `export: [JwtModule]`. change JwtProviderModule like below.
```
@Module({
  imports: [JwtModule.regster(...)]
  exports: [JwtModule]
})
export class JwtProviderModule {}
```

and then, main.ts
```
bootstrap(AuthModule).finally(() => {
})
```
some-service.ts
```
@Injectable()
export class SomeService {
  constructor(
    private readonly jwtService: JwtService,
  ) {}
  async sign() {
    return await this.jwtService.signAsync(payload)
  }
}
  
```
it works. :)
