### ISSUE TITLE
jwt module shoud  extends ConfigurableModuleClass

### ISSUE THREAD

**Issue by floross** [nestjs/jwt#1064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

JwtModule does not use the nestjs v9 ModuleOptionsBuilder. That said we cannot use the providers from the parent module when we want to pass the options from a parent module (as describe here: nestjs/nest#9935).

### Minimum reproduction code

https://github.com/nestjs/nest/pull/9935

### Steps to reproduce

Try to use this kind of configuration described in the merged pull request.

```ts
         JwtModule.registerAsync({
          useFactory(opt: AuthenticationOptions) {
            return opt.jwtOptions;
          },
          inject: [AuthenticationOptions],
        }),
```

When using this code we cannot inject `JwtService` in our service from our parent module

### Expected behavior

Allow `provideInjectionTokensFrom` to be able to use the config providers from a parent module 

### Package version

9.0.0

### NestJS version

9.0.11

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/jwt/pull/1065
