### ISSUE TITLE
vulnerability in dependancy jsonwebtoken <=8.5.1 

### ISSUE THREAD

**Issue by behnamshayani-accenture** [nestjs/jwt#1152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There is a security issue in dependency jsonwebtoken
Updating to jsonwebtoken's latest version 9.0.0 resolves the vulnerability
Vulnerability details : https://github.com/advisories/GHSA-27h2-hvpr-p74q

### Minimum reproduction code

https://github.com/advisories/GHSA-27h2-hvpr-p74q

### Expected behavior

updating jsonwebtoken to latest version 9.0.0

### Package version

9.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
this will be fixed by PR #1155
