### ISSUE TITLE
Updating `jsonwebtoken` dependency

### ISSUE THREAD

**Issue by borismih** [nestjs/jwt#1153]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This moring we had a failed dependency security scanning, due to an high vulrnerability risk with this package. By investigatigating, we got to the conclusion that the package `jsonwebtoken` has that vulnerability, which is a dependacy of this package.
This is the link to the vulnerability: https://github.com/advisories/GHSA-27h2-hvpr-p74q .

There is a new version of the `jsonwebtoken` which should resolve this issue. So my question is: Will @nestjs/jwt package support the newest version of `jsonwebtoken` which is v9.0.0 in near future?

Thank you in advance.

### Describe the solution you'd like

The dependency `jsonwebtoken` should be updated to version v9.0.0

### What is the motivation / use case for changing the behavior?

This will directly affect our production build, but passing the security scan, since we would love to continue using this package.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/jwt/issues/1153

**Comment by abdul99j** [comment]
@kamilmysliwiec why this is closed, vulnerability still exists in the package.

**Comment by micalevisk** [comment]
@abdul99j this was closed because it's a duplicate of #1152
