### ISSUE TITLE
Update `@types/jsonwebtoken` to ^9.0.0

### ISSUE THREAD

**Issue by yanekyuk** [nestjs/jwt#1184]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

9.0.0 -> 10.0.1

### Describe the regression

Although the library `jsonwebtoken` is upgraded to version 9, the type declaration library `@types/jsonwebtoken` is still on 8.5.9.

### Minimum reproduction code

```ts
@Module({
  imports: [
    JwtModule.registerAsync({
      useFactory () {
        return {
          secret: SECRET,
          // allowInsecureSizes is not in the `@types/jsonwebtoken` type declaration file.
          signOptions: { algorithm: 'HS256', allowInsecureKeySizes: true },
        };
      },
    }),
  ]
})
```

### Expected behavior

`allowInsecureKeySizes` should be autocompleted in `jwt.SignOptions` type.

**Comment by yanekyuk** [comment]
Already being reviewed at #1161

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/jwt/pull/1161
