### ISSUE TITLE
secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by dc980806** [nestjs/jwt#1228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This code doesn't work,  When calling the sign method，thorw an error: secretOrPrivateKey must have a value

```
// auth.module.ts
@Module({
  imports: [
    JwtModule.register({
      secret: 'test',
        signOptions: {
          expiresIn: '60s'
        }
    })
  ],
  controllers: [ AuthController ],
  providers: [ LocalStrategy, ConfigService, JwtService, AuthService ] 
})
```

```
// auth.service.ts
import { Injectable } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';

@Injectable()
export class AuthService {
  constructor(
    private readonly jwtService: JwtService
  ) { }

  async login(user: {username: string, id: string}) {
    const payload = { username: user.username, sub: user.id };
    return {
      access_token: this.jwtService.sign(payload)
    };
  }
}
```

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/35423514/223070085-d268eea5-08cc-46b8-b3eb-f8f2b59f1e51.png">

but if pass parameters to sign method, It work

```
import { Injectable } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';

@Injectable()
export class AuthService {
  constructor(
    private readonly jwtService: JwtService
  ) { }

  async login(user: {username: string, id: string}) {
    const payload = { username: user.username, sub: user.id };
    return {
      access_token: this.jwtService.sign(payload, {
        secret: 'test',
        expiresIn: '60s'
      })
    };
  }
}
```

Will it be caused by version differences between various dependencies?
<img width="602" alt="image" src="https://user-images.githubusercontent.com/35423514/223071575-4bfeffaf-1b92-454f-a45e-6a615f38e6b7.png">

### Minimum reproduction code

none

### Expected behavior

Normal return jwt

### Package version

10.0.2

### NestJS version

9.0.0

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I wrote it according to the official document, so I'm a little confused

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
