### ISSUE TITLE
secretOrPrivateKey has a minimum key size of 2048 bits for RS256 after upgrade to nest/jwt 10.0.2

### ISSUE THREAD

**Issue by conioX** [nestjs/jwt#1230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

failed to generate token and throw exception secretOrPrivateKey has a minimum key size of 2048 bits for RS256. this issue only happen when running inside docker alpine (FROM node:18.14-alpine3.17) normal run on my local

### Minimum reproduction code

Sorry repo in my company git

### Steps to reproduce

1. upgrade package.json like below : 

    "@nestjs/jwt": "10.0.2"
    "passport-jwt": "^4.0.1",
    "@types/passport-jwt": "^3.0.8",

### Expected behavior

normal like   "@nestjs/jwt": "9.0.0",

### Package version

10.0.2

### NestJS version

9.3.9

### Node.js version

18.14

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by conioX** [comment]
this issue come from https://github.com/auth0/node-jsonwebtoken/issues/888

**Comment by AminAzGol** [comment]
I have this issue on node `v20.11.0`, yet it works fine with `v19.3.0`
