### ISSUE TITLE
BigInt not supported

### ISSUE THREAD

**Issue by ikbenignace** [nestjs/jwt#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When signing a jwt token with a BigInt, it will not be singed correctly.

For example: 869976676795383809 will be signed as 869976676795383800

### Minimum reproduction code

Not neccesary

### Expected behavior

It should just be signed as 869976676795383800

### Package version

latest

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
