### ISSUE TITLE
type error while using `expiresIn` in `signAsync`

### ISSUE THREAD

**Issue by aayushchugh** [nestjs/jwt#1369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am not able to use `expiresIn` option while signing a token

Getting error

```
No overload matches this call.
  Overload 1 of 2, '(payload: string, options?: Omit<JwtSignOptions, keyof SignOptions>): Promise<string>', gave the following error.
    Argument of type '{ secret: string; expiresIn: string; }' is not assignable to parameter of type 'Omit<JwtSignOptions, keyof SignOptions>'.
      Object literal may only specify known properties, and 'expiresIn' does not exist in type 'Omit<JwtSignOptions, keyof SignOptions>'.
  Overload 2 of 2, '(payload: object | Buffer, options?: JwtSignOptions): Promise<string>', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'object | Buffer'.ts(2769)
```

In following code

```typescript
const accessToken = this.jwtService.signAsync(String(user.id), {
     secret: accessTokenPublicKey,
     expiresIn: "15m",
});
```

Code for module

```typescript
@Module({
	controllers: [AuthController],
	providers: [AuthService],
	imports: [JwtModule.register({ global: true, signOptions: { algorithm: "RS256" } })],
})
export class AuthModule {}
```

I can use `expiresIn` in `JwtModule.register()` but now while using it in service

### Minimum reproduction code

https://github.com/maya-manager/server/blob/aayushchugh/login/src/modules/auth/auth.service.ts#L164-L167

### Expected behavior

I should be able to use `expiresIn` without any type errors

### Package version

10.1.0

### NestJS version

10.0.5

### Node.js version

18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

<img width="718" alt="image" src="https://github.com/nestjs/jwt/assets/69336518/54bb4586-c51a-4d49-ab42-32c57b59f0a0">

Also, VScode is only showing autocomplete for these 2 options

<img width="843" alt="image" src="https://github.com/nestjs/jwt/assets/69336518/cd4b690d-0c0a-41b4-97d9-68c5970a0de9">

Here there are two `signAsync` and in the upper one you are using `Omit`. I think `Omit` is removing all the types from `SignOptions` and I can't use `expiresIn`

<img width="889" alt="image" src="https://github.com/nestjs/jwt/assets/69336518/79f291d6-6e88-4b61-bd40-8154964495fd">

**Comment by aayushchugh** [comment]
After downgrading the package to `10.0.3` the problem was solved and I was able to access `expiresIn`

**Comment by kamilmysliwiec** [comment]
PRs are more than welcome 🙏

**Comment by aayushchugh** [comment]
@kamilmysliwiec Assign this to me please

**Comment by Hender-hs** [comment]
Does your code run in `10.0.3` version? Test it. 
It must break.

  
JsonWebToken breaks when you use payload as string and set a "invalid" options, such as: expiresIn, notBefore, etc.  
Except: privateKey and secret.  

See /jsonwebtoken/sign.js

**Comment by aayushchugh** [comment]
@Hender-hs My code was working in `10.0.3` without any problem

**Comment by tianangthang7** [comment]
why don't we fix that

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/jwt/pull/1370
