### ISSUE TITLE
Expose internal Jsonwebtoken errors from @Next/jwt

### ISSUE THREAD

**Issue by Najtu** [nestjs/jwt#1437]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When trying to use the TokenExpiredError from jsonwebtoken i discovered that jsonwebtoken has to match its module version with the version used in @nest/jwt.

In my case
```
error instanceof TokenExpiredError
```
was not working because the installed jsonwebtoken in my project was of version 9.0.2 while in @nest/jwt it was 9.0.0

### Describe the solution you'd like

expose jsonwebtoken errors from @nest/jwt

```
export {JsonWebTokenError, NotBeforeError, TokenExpiredError} from "jsonwebtoken"
```

I'm not sure if exposing this in the index file is the right solution, so I submit this request to discuss.

### What is the motivation / use case for changing the behavior?

This would help using "instanceof" to define custom errors based on the defined instance without the need of adding the jsonwebtoken package to the project dependencies and matching the version with @nest/jwt

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/jwt/pull/1438
