### ISSUE TITLE
Issue: Missing 'requestProperty' in @nestjs/jwt Library

### ISSUE THREAD

**Issue by alain-guillon-it** [nestjs/jwt#1487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello, I am an intern at a company where I am currently working on developing a multi-organizational software solution. I am facing an issue with the '**requestProperty**' property, which is available in the express-jwt dependency but is missing in @nestjs/jwt.

I would like to inquire about the current relevance of this property and, if it is no longer available, how I can obtain a similar functionality.

The specific property I'm referring to is as follows:

_**requestProperty?: string (optional): Name of the property in the request object where the payload is set. Default to req.auth.**_

Is it possible to get some feedback on this matter? Thank you.

### Minimum reproduction code

https://gist.github.com/alain-guillon-it/5181b5b4c41cacba13e27c107d1ecb38

### Expected behavior

How to used the property in NestJS please ?

### Package version

```json
{
  "dependencies": {
    "@nestjs/common": "^10.2.8",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.2.8",
    "@nestjs/devtools-integration": "^0.1.5",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/mongoose": "^10.0.2",
    "@nestjs/passport": "^10.0.0",
    "@nestjs/platform-express": "^10.2.8",
    "@nestjs/serve-static": "^4.0.0",
    "@nestjs/swagger": "^7.1.15",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "class-validator-mongo-object-id": "^1.4.0",
    "jsonwebtoken": "^9.0.2",
    "moment": "^2.29.4",
    "mongoose": "^7.6.3",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@compodoc/compodoc": "^1.1.22",
    "@nestjs/cli": "^10.2.1",
    "@nestjs/schematics": "^10.0.3",
    "@nestjs/testing": "^10.2.8",
    "@types/express": "^4.17.21",
    "@types/jest": "^29.5.8",
    "@types/node": "^20.9.0",
    "@types/passport-jwt": "^3.0.13",
    "@types/passport-local": "^1.0.38",
    "@types/supertest": "^2.0.16",
    "@typescript-eslint/eslint-plugin": "^6.10.0",
    "@typescript-eslint/parser": "^6.10.0",
    "eslint": "^8.53.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.1",
    "jest": "^29.7.0",
    "prettier": "^3.0.3",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.1",
    "ts-loader": "^9.5.0",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.2.2"
  }
}
```

### NestJS version

10.1.18

### Node.js version

18.16.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
