### ISSUE TITLE
JsonWebTokenError: secretOrPublicKey must be an asymmetric key when using RS256

### ISSUE THREAD

**Issue by cibilex** [nestjs/jwt#1552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I tried to use RS256 algorithm instead of HS256.JwtService successfully creates token with sign but always throw error when I try to verify it.

I put the repository link to below.In auth.Requests can be sent in /http/auth.http and error throws at `auth.guard.ts`.

Note:Branch name: nest-rs256-err
[System Information]
OS Version     : macOS 22.3.0
NodeJS Version : v21.5.0
NPM Version    : 10.3.0 

[Nest CLI]
Nest CLI Version : 10.3.0 

[Nest Platform Information]
platform-express version : 10.3.0
platform-fastify version : 10.3.0
mapped-types version     : 2.0.4
schematics version       : 10.1.0
testing version          : 10.3.0
common version           : 10.3.0
core version             : 10.3.0
jwt version              : 10.2.0
cli version              : 10.3.0

[Warnings]
The following packages are not in the same minor version
This could lead to runtime errors
* Under version 10.3
- @nestjs/platform-express 10.3.0
- @nestjs/platform-fastify 10.3.0
- @nestjs/common 10.3.0
- @nestjs/core 10.3.0
* Under version 10.1
- @nestjs/schematics 10.1.0

### Minimum reproduction code

https://github.com/cibilex/nest-authorization/tree/rs256

### Steps to reproduce

1. npm i
2. npm run start:dev

### Expected behavior

It must correctly verifies the token instead of throw error :)
Also I guess error messages are not that clear to understand.

### Package version

10.3.0

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

### Other

best regards

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
