### ISSUE TITLE
Error: secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by joy-stacks** [nestjs/jwt#1616]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the regression

already imports

@Module({
  imports: [
    UsersModule,
    JwtModule.register({
      global: true,
      secret: jwtConstants.secret,
      signOptions: { expiresIn: '60s' },
    }),
  ],
  providers: [AuthService],
  controllers: [AuthController],
  exports: [AuthService],
})
export class AuthModule {}

why?  Error: secretOrPrivateKey must have a value

### Minimum reproduction code

```ts

```

### Expected behavior

success

**Comment by miyaohua** [comment]
token: this.jwtService.sign(payload, { secret: jwtConstants.secret, expiresIn: jwtConstants.expiresIn })
Provide the second parameter key as secret
