### ISSUE TITLE
Bug with `registerAsync` and `global` and guards

### ISSUE THREAD

**Issue by Makoehle** [nestjs/jwt#1694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- Register `JwtModule` with `global` and `app.module`
- Nest can't resolve dependencies of the AuthGuard (?). If JwtService is a provider, is it part of the current GuardedRouteModule?

### Minimum reproduction code

https://github.com/Makoehle/nest-jwt/blob/ca59bda33ed4d7ba09ddd39d888612cebdb6210e/src/app.module.ts#L12

### Steps to reproduce

1. pnpm i
2. pnpm start:dev

### Expected behavior

When having `global` activated I expect that the module can resolve `JwtService`.

### Package version

10.2.0

### NestJS version

10.0.0

### Node.js version

20.12.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

WSL2

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
