### ISSUE TITLE
How to handle a route that authentication is optional?

### ISSUE THREAD

**Issue by seekcx** [nestjs/jwt#22]
I'd like to create routes that authenticates req.user for authenticated users but still allow non authenticated users to access the route. 

Would anybody be as kind to give me a workaround?

**Comment by kamilmysliwiec** [comment]
You can simply extend `AuthGuard` and `return true` even if `canActivate` throws an exception/returns false. :)

**Comment by Veetaha** [comment]
@kamilmysliwiec Could you please attach passport `info` object to the exception that you throw, because I need to know why the exception was actually thrown.
