### ISSUE TITLE
Error: Nest can't resolve dependencies of the UsersService (?). Please make sure that the argument studentsModel at index [0] is available in the AppModule context

### ISSUE THREAD

**Issue by salil20495** [nestjs/jwt#256]
Am trying JWT in my code and i got an error of -
:Error: Nest can't resolve dependencies of the UsersService (?). Please make sure that the argument studentsModel at index [0] is available in the AppModule context

Potential solutions:
- If studentsModel is a provider, is it part of the current AppModule?
- If studentsModel is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing studentsModel */ ]
  })

But i didn't understand how to solve this.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
