### ISSUE TITLE
JwtModule.register() The method didn't work

### ISSUE THREAD

**Issue by MutelyMilo** [nestjs/jwt#340]
`JwtModule.register({
      secret: "configuration.auth.secretKey",
      signOptions: { expiresIn: '1s' },
    })`

This token never expires
Then I tried the secret change, and token is still valid

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
