### ISSUE TITLE
Unable to verify tokens when using Buffer/base64 encoded public key

### ISSUE THREAD

**Issue by ceefour** [nestjs/jwt#447]
## I'm submitting a...

- [x] Bug report

## Current behavior

Unable to verify tokens when using Buffer/base64 encoded public key -> throws Invalid algorithm error.

## Expected behavior

Public key as Buffer (direct binary array) should be supported.

## Minimal reproduction of the problem with instructions

Use the following AuthModule:

```ts
import { Module } from '@nestjs/common';
import { JwtModule } from '@nestjs/jwt';
// import pemtools from 'pemtools';

let publicKey: string | Buffer | null = process.env.JWT_PUBLIC_KEY;
if (process.env.JWT_PUBLIC_KEY && !process.env.JWT_PUBLIC_KEY.startsWith('-----')) {
  publicKey = Buffer.from(process.env.JWT_PUBLIC_KEY, 'base64');
  // Workaround:
  // publicKey = pemtools(publicKey, 'PUBLIC KEY').toString();
}
// console.debug('publicKey=', publicKey);

@Module({
  imports: [
    JwtModule.register({
      publicKey,
    })
  ],
})
export class AuthModule {}
```

When publicKey is a buffer, jwtService.verify(...) will always fail due to 'Invalid algorithm', however if we pass a PEM-encoded string, it will work.

## What is the motivation / use case for changing the behavior?

One-line Base64 encoded string is much easier to put into environment variable (12-factor app principle) than PEM-encoded multiline string.

## Environment

Nest version: nestjs/jwt 7.1.0

 
For Tooling issues:
- Node version: 12.19.0  
- Platform: Ubuntu 20.04.1 

Others:

Workaround is to use npm package `pemtools`:

```ts
import pemtools from 'pemtools';

let publicKey: string | Buffer | null = process.env.JWT_PUBLIC_KEY;
if (process.env.JWT_PUBLIC_KEY && !process.env.JWT_PUBLIC_KEY.startsWith('-----')) {
  publicKey = Buffer.from(process.env.JWT_PUBLIC_KEY, 'base64');
  // Workaround:
  publicKey = pemtools(publicKey, 'PUBLIC KEY').toString();
}
```

However this is unnecessary as what it does is re-encoding Buffer which is already binary into PEM-encoded string which will be decoded into binary string again.

Related to #94.

**Comment by kamilmysliwiec** [comment]
I believe that this issue should be reported in this repo https://github.com/auth0/node-jsonwebtoken. `@nestjs/jwt` package simply passes down all options to the `jsonwebtoken`
