### ISSUE TITLE
Tests are written with numerous gross mistakes

### ISSUE THREAD

**Issue by KostyaTretyak** [nestjs/jwt#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Tests are written with numerous gross mistakes. For example:
1. In this code and all async tests with `.resolves.` / `.rejects.` syntax:

https://github.com/nestjs/jwt/blob/c2c8a80f3edda96952e3295a36de0df892129f98/lib/jwt.service.spec.ts#L53-L57

You need to put `await` before `expect`. See docs for [Testing Asynchronous Code](https://jestjs.io/docs/asynchronous#asyncawait).

2. After that, the tests start to crash with a timeout. This is because the wrong configuration of jest spy. As far as I understand, jest spy is not used at all.

3. If you remove jest spy, the tests begin to fail due to incorrect expectations. For example `sign()` returns token, but here expected secret:

https://github.com/nestjs/jwt/blob/c2c8a80f3edda96952e3295a36de0df892129f98/lib/jwt.service.spec.ts#L79-L81

4. And so on...

### Expected behavior

Tests must be written accurately and correctly.

### Package version

8.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Tests were added via external contribution as part of this commit https://github.com/nestjs/jwt/commit/9bae00762fd7ff9b29cec04a98562c5ab95a864a. Feel free to create a follow-up PR to improve them.
