### ISSUE TITLE
Unexpected behavior when getting a value from .env file for expiresIn property via the ConfigModule / ConfigService

### ISSUE THREAD

**Issue by zzpzaf** [nestjs/jwt#849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It assigns zero to the expiresIn property, instead of the number of seconds (JWT_EXP=60) provided in the parameter in the .env file. However, when an s is added to the parameter value (JWT_EXP=60s) it works OK.

Some more details
The strange thing happens at that line 
signOptions: { expiresIn: configService.get('JWT_EXP', 60) },

It was refusing to get the JWT_EXP value from the .env file: 
JWT_EXP=60
until added the ‘s’ as the seconds indicator, so I changed it to:
JWT_EXP=60s
After that it works OK

Surprisingly, I also noticed that when the JWT_EXP env variable is missing, e.g. I renamed it to
JWT_EXPXXX=60s
the default number value provided as second parameter in configService.get, works OK as it is expected.

Just also to mention, that as an error message I got back trying to solve the issue, the 
 "expiresIn" should be a number of seconds or string representing a timespan eg: "1d", "20h", 60 ….

### Minimum reproduction code

https://gist.github.com/zzpzaf/7fc9bba6c294674b3fa355f44e7cc52e, https://gist.github.com/zzpzaf/27ce9f2847ce01952e510ff70d1edb3c, https://gist.github.com/zzpzaf/d558b7376e03dfb18f986c0a20bf2bb0

### Expected behavior

It should read the number of seconds provided correctly, as expiration time, without s - seconds indicator 

### Package version

8.0.0

### NestJS version

8.1.5

### Node.js version

16.11.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I  also have a post at Discord

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
